# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # check https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pycqa/isort
    rev: 9.0.0a3
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black"]
-   repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
    -   id: black
        language_version: python3.13
# -   repo: local
#     hooks:
#     -   id: pytest
#         entry: pytest
#         language: system
#         pass_filenames: false
#         always_run: true # Elke commit runnen, ook als er geen bestanden zijn gewijzigd
#         args: ["tests/"]

#     -  id: pylint
#        entry: pylint
#        language: system
#        types: [python]
#        args: ["-rn", "-sn", "--recursive=y"]
