services:
  # PostgreSQL database for our services
  database:
    build: ./backend-database
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql
    env_file:
      - ./backend-database/.env

  # MLFlow server for experiment tracking (uses the database)
  experiment-tracking:
    build: ./backend-service-experiment-tracking
    ports:
      - "${MLFLOW_HOST_PORT:-5001}:5000"
    depends_on:
      - database

  # prefect server
  orchestration:
    build: ./backend-service-orchestration
    ports:
      - 4200:4200
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_UI_API_URL=http://localhost:4200/api

  # model training service
  # This runs a main.py which runs multiple scripts to preprocess data, train a model, and log the results to MLFlow.
  train-deploy:
      build: ./train-and-deploy
      volumes:
        - ./Data:/app/data:ro
        - ./Models:/app/models
      environment:
        - PREFECT_API_URL=http://orchestration:4200/api
        - MLFLOW_TRACKING_URI=http://experiment-tracking:5000
      depends_on:
        - experiment-tracking
        - orchestration
        - database
      restart: on-failure

  # grafana server
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    volumes:
      - batch-data:/batch-data
      # use local bind mounts
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - grafana-data-dashboards:/opt/grafana/dashboards
    ports:
      - "3400:3000"

  # For testing and development
  web-api-dev:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    volumes:
      - .:/workspace:cached
    command: sleep infinity

  batch-dev:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    volumes:
      - .:/workspace:cached
    command: sleep infinity

# Product Ready Services - use instead of dev
  web-api:
    build: ./deployment-web-api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://experiment-tracking:5000
    depends_on:
      - experiment-tracking

  # Batch Service
  batch-score:
    build: ./deployment-batch
    volumes:
      - batch-data:/batch-data
    environment:
      - PREFECT_API_URL=http://orchestration:4200/api
      - MLFLOW_TRACKING_URI=http://experiment-tracking:5000
    depends_on:
      - experiment-tracking
      - orchestration
      - database
    restart: on-failure

volumes:
  postgres-data:
  grafana-data-dashboards:
  batch-data:
